/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myfirstapplication;

import java.awt.*;
import java.awt.event.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;
import javax.swing.event.*;

/**
 *
 * @author ethan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private void jClientInfoListValueChanged(ListSelectionEvent e) {
        int index = jClientInfoList.getSelectedIndex();
        Person person = BankClients.getElementAt(index);

        setEdit(person);
    }

    private void setEdit(Person person) {
        jFnameTextField.setText(person.getFirstName());
        jSnameTextField.setText(person.getSurname());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        jDOBTextField.setText(person.getDOB().format(formatter));

        IAddress address = person.getHomeAddress();

        jHouseNumTextField.setText(String.valueOf(address.getHouse_no()));
        jStreetTextField.setText(address.getStreet());
        jPostCodeTextField.setText(address.getPost_code());
        jTownTextField.setText(address.getTown());
        jCountryTextField.setText(address.getCountry());
    }

    private void jFindButtonPressed(ActionEvent e) {
        Person newClient = fieldsToPerson();

        jClientInfoList.setSelectedIndex(BankClients.getIndexOf(newClient));
    }

    private Person fieldsToPerson() {
        Person newClient = new Person();

        LocalDate date = LocalDate.now();

        newClient.Edit(jFnameTextField.getText(), jSnameTextField.getText(), jDOBTextField.getText(), date.format(DateTimeFormatter.ofPattern("d/MM/uuuu")));

        newClient.editAddress("", Integer.valueOf(jHouseNumTextField.getText()), jStreetTextField.getText(), "", jPostCodeTextField.getText(), jTownTextField.getText(), jCountryTextField.getText());

        return newClient;
    }

    public MainJFrame() {
        
        theHeadOfficeBranch = new Branch();
        theHeadOfficeBranch.LoadFromFile("Branches/headOffice.txt");
        
        theUser = new User();

        BankClients = new CustomerList("Accounts/BankClients.txt");
        
        BankBranches = new BranchList();
        
        // Tab Code
        jTabInMemory = new java.awt.Component[15];

        initComponents();

        int nonLoginTabs = jMainTabbedPane.getTabCount() - 1;

        for(int i = 0; i < nonLoginTabs; i++){
            jTabInMemory[i] = (jMainTabbedPane.getComponentAt(1));
            jMainTabbedPane.remove(1);
        }
        
        jMainTabbedPane.setSelectedIndex(0);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Ethan Deeley (2282321)
    private void initComponents() {
        jMenuBarMain = new JMenuBar();
        jMenu1 = new JMenu();
        jMenu2 = new JMenu();
        jMainPanel = new JPanel();
        jStatusPanel = new JPanel();
        jStatusMessageLabel = new JLabel();
        jStatusAnimationLabel = new JLabel();
        jProgressCompletionBar = new JProgressBar();
        jMainTabbedPane = new JTabbedPane();
        jLoginPanel = new JPanel();
        jNameLabel = new JLabel();
        jNameTextField = new JTextField();
        jLoginButton = new JButton();
        jPasswordLabel = new JLabel();
        jPasswordTextField = new JPasswordField();
        jRegisterButton = new JButton();
        jLogOutButton = new JButton();
        jCalculatorPanel = new JPanel();
        jInput1Label = new JLabel();
        jInput2Label = new JLabel();
        jOutputLabel = new JLabel();
        jInput1TextField = new JTextField();
        jInput2TextField = new JTextField();
        jOutputTextField = new JTextField();
        jAddButton = new JButton();
        jSubtractButton = new JButton();
        jMultButton = new JButton();
        jDivButton = new JButton();
        jPowerButton = new JButton();
        jCylinderVolumeButton = new JButton();
        jSphereVolumeButton = new JButton();
        jPyramidVolumeButton = new JButton();
        jClientListPanel = new JPanel();
        scrollPane1 = new JScrollPane();
        jClientInfoList = new JList<>(BankClients);
        jFnameLabel3 = new JLabel();
        jSnameLabel = new JLabel();
        jFnameTextField = new JTextField();
        jSnameTextField = new JTextField();
        jDOBLabel = new JLabel();
        jDOBTextField = new JTextField();
        jHouseNumLabel = new JLabel();
        jHouseNumTextField = new JTextField();
        jStreetLabel = new JLabel();
        jStreetTextField = new JTextField();
        jTownLabel = new JLabel();
        jPostCodeLabel = new JLabel();
        jTownTextField = new JTextField();
        jPostCodeTextField = new JTextField();
        jCountryLabel = new JLabel();
        jCountryTextField = new JTextField();
        jSaveButton = new JButton();
        jRemoveButton = new JButton();
        jFindButton = new JButton();
        jHeadOfficePanel = new JPanel();
        jHeadOfficeButton = new JButton();
        jHeadOfficeTextArea = new JTextArea();
        jEditHeadOfficePanel = new JPanel();
        JNameEditLabel = new JLabel();
        jNameEditTextField = new JTextField();
        jOpeningHoursEditLabel = new JLabel();
        jOpeningHoursEditTextField = new JTextField();
        jHouseNoEditLabel = new JLabel();
        jStreetEditLabel = new JLabel();
        jCityEditLabel = new JLabel();
        jPostcodeEditLabel = new JLabel();
        jCountryEditLabel = new JLabel();
        jHouseNoEditTextField = new JTextField();
        jStreetEditTextField = new JTextField();
        jCityEditTextField = new JTextField();
        jPostCodeEditTextField = new JTextField();
        jCountryEditTextField = new JTextField();
        jButton1 = new JButton();
        jBranchListPenel = new JPanel();
        scrollPane2 = new JScrollPane();
        jBranchListTextArea = new JTextArea();
        JBranchListDisplay = new JButton();
        jAddBranchPanel = new JPanel();
        panel2 = new JPanel();
        jFnameLabel2 = new JLabel();
        jSnameLabel2 = new JLabel();
        jFnameTextField2 = new JTextField();
        jSnameTextField2 = new JTextField();
        jDOBLabel2 = new JLabel();
        jDOBTextField2 = new JTextField();
        jHouseNumLabel2 = new JLabel();
        jHouseNumTextField2 = new JTextField();
        jStreetLabel2 = new JLabel();
        jStreetTextField2 = new JTextField();
        jTownLabel2 = new JLabel();
        jPostCodeLabel2 = new JLabel();
        jTownTextField2 = new JTextField();
        jPostCodeTextField2 = new JTextField();
        jCountryLabel2 = new JLabel();
        jCountryTextField2 = new JTextField();
        label1 = new JLabel();
        jSaveBranchButton = new JButton();
        panel3 = new JPanel();
        JNameEditLabel2 = new JLabel();
        jNameEditTextField2 = new JTextField();
        jOpeningHoursEditLabel2 = new JLabel();
        jOpeningHoursEditTextField2 = new JTextField();
        jHouseNoEditLabel2 = new JLabel();
        jStreetEditLabel2 = new JLabel();
        jCityEditLabel2 = new JLabel();
        jPostcodeEditLabel2 = new JLabel();
        jCountryEditLabel2 = new JLabel();
        jHouseNoEditTextField2 = new JTextField();
        jStreetEditTextField2 = new JTextField();
        jCityEditTextField2 = new JTextField();
        jPostCodeEditTextField2 = new JTextField();
        jCountryEditTextField2 = new JTextField();
        label2 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0x4a4a48));
        var contentPane = getContentPane();

        //======== jMenuBarMain ========
        {
            jMenuBarMain.setBackground(new Color(0x4a4a48));
            jMenuBarMain.setBorder(new LineBorder(new Color(0x4a4a48)));
            jMenuBarMain.setForeground(new Color(0x566246));

            //======== jMenu1 ========
            {
                jMenu1.setBackground(new Color(0x000041));
                jMenu1.setText("File");
            }
            jMenuBarMain.add(jMenu1);

            //======== jMenu2 ========
            {
                jMenu2.setText("Edit");
            }
            jMenuBarMain.add(jMenu2);
        }
        setJMenuBar(jMenuBarMain);

        //======== jMainPanel ========
        {

            //======== jStatusPanel ========
            {
                jStatusPanel.setBackground(new Color(0x4a4a48));
                jStatusPanel.setBorder(LineBorder.createBlackLineBorder());
                jStatusPanel.setFont(new Font("Tw Cen MT", Font.BOLD, 14));

                //---- jStatusMessageLabel ----
                jStatusMessageLabel.setFont(new Font("Tw Cen MT", Font.BOLD, 14));
                jStatusMessageLabel.setText("My First Application is running.");

                //---- jStatusAnimationLabel ----
                jStatusAnimationLabel.setText("jLabel2");

                GroupLayout jStatusPanelLayout = new GroupLayout(jStatusPanel);
                jStatusPanel.setLayout(jStatusPanelLayout);
                jStatusPanelLayout.setHorizontalGroup(
                    jStatusPanelLayout.createParallelGroup()
                        .addGroup(jStatusPanelLayout.createSequentialGroup()
                            .addGroup(jStatusPanelLayout.createParallelGroup()
                                .addComponent(jStatusMessageLabel)
                                .addComponent(jStatusAnimationLabel)
                                .addComponent(jProgressCompletionBar, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 530, Short.MAX_VALUE))
                );
                jStatusPanelLayout.setVerticalGroup(
                    jStatusPanelLayout.createParallelGroup()
                        .addGroup(jStatusPanelLayout.createSequentialGroup()
                            .addComponent(jStatusMessageLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jStatusAnimationLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jProgressCompletionBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 35, Short.MAX_VALUE))
                );
            }

            GroupLayout jMainPanelLayout = new GroupLayout(jMainPanel);
            jMainPanel.setLayout(jMainPanelLayout);
            jMainPanelLayout.setHorizontalGroup(
                jMainPanelLayout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jStatusPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
            jMainPanelLayout.setVerticalGroup(
                jMainPanelLayout.createParallelGroup()
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jStatusPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 246, Short.MAX_VALUE))
            );
        }

        //======== jMainTabbedPane ========
        {

            //======== jLoginPanel ========
            {

                //---- jNameLabel ----
                jNameLabel.setText("Name:");
                jNameLabel.setToolTipText("");

                //---- jLoginButton ----
                jLoginButton.setText("Login");
                jLoginButton.addActionListener(e -> jLoginButtonActionPerformed(e));

                //---- jPasswordLabel ----
                jPasswordLabel.setText("Password:");

                //---- jRegisterButton ----
                jRegisterButton.setText("Register");
                jRegisterButton.addActionListener(e -> jRegisterButtonActionPerformed(e));

                //---- jLogOutButton ----
                jLogOutButton.setText("Log Out");
                jLogOutButton.addActionListener(e -> jLogOutButtonActionPerformed(e));

                GroupLayout jLoginPanelLayout = new GroupLayout(jLoginPanel);
                jLoginPanel.setLayout(jLoginPanelLayout);
                jLoginPanelLayout.setHorizontalGroup(
                    jLoginPanelLayout.createParallelGroup()
                        .addGroup(jLoginPanelLayout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addGroup(jLoginPanelLayout.createParallelGroup()
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addComponent(jLoginButton, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jRegisterButton))
                                .addGroup(jLoginPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordTextField, GroupLayout.Alignment.TRAILING)
                                    .addComponent(jNameTextField, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLogOutButton))
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(jNameLabel))
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jPasswordLabel)))
                            .addContainerGap(408, Short.MAX_VALUE))
                );
                jLoginPanelLayout.setVerticalGroup(
                    jLoginPanelLayout.createParallelGroup()
                        .addGroup(jLoginPanelLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jNameLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPasswordTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jLoginPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLoginButton)
                                .addComponent(jRegisterButton))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLogOutButton)
                            .addContainerGap(286, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Login", jLoginPanel);

            //======== jCalculatorPanel ========
            {

                //---- jInput1Label ----
                jInput1Label.setText("Input 1");

                //---- jInput2Label ----
                jInput2Label.setText("Input 2");

                //---- jOutputLabel ----
                jOutputLabel.setText("Output");

                //---- jInput1TextField ----
                jInput1TextField.setText("0.0");
                jInput1TextField.addActionListener(e -> jInput1TextFieldActionPerformed(e));

                //---- jInput2TextField ----
                jInput2TextField.setText("0.0");

                //---- jOutputTextField ----
                jOutputTextField.setText("0.0");
                jOutputTextField.addActionListener(e -> jOutputTextFieldActionPerformed(e));

                //---- jAddButton ----
                jAddButton.setText("+");
                jAddButton.addActionListener(e -> jAddButtonActionPerformed(e));

                //---- jSubtractButton ----
                jSubtractButton.setText("-");
                jSubtractButton.addActionListener(e -> jSubtractButtonActionPerformed(e));

                //---- jMultButton ----
                jMultButton.setText("*");
                jMultButton.addActionListener(e -> jMultButtonActionPerformed(e));

                //---- jDivButton ----
                jDivButton.setText("/");
                jDivButton.addActionListener(e -> jDivButtonActionPerformed(e));

                //---- jPowerButton ----
                jPowerButton.setText("X^y");
                jPowerButton.addActionListener(e -> jPowerButtonActionPerformed(e));

                //---- jCylinderVolumeButton ----
                jCylinderVolumeButton.setText("Cylinder Vol");
                jCylinderVolumeButton.addActionListener(e -> jCylinderVolumeButtonActionPerformed(e));

                //---- jSphereVolumeButton ----
                jSphereVolumeButton.setText("Sphere Vol");
                jSphereVolumeButton.addActionListener(e -> jSphereVolumeButtonActionPerformed(e));

                //---- jPyramidVolumeButton ----
                jPyramidVolumeButton.setText("Pyramid Vol");
                jPyramidVolumeButton.addActionListener(e -> jPyramidVolumeButtonActionPerformed(e));

                GroupLayout jCalculatorPanelLayout = new GroupLayout(jCalculatorPanel);
                jCalculatorPanel.setLayout(jCalculatorPanelLayout);
                jCalculatorPanelLayout.setHorizontalGroup(
                    jCalculatorPanelLayout.createParallelGroup()
                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jCalculatorPanelLayout.createParallelGroup()
                                .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                    .addGroup(jCalculatorPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                            .addComponent(jInput2Label)
                                            .addGap(18, 18, 18)
                                            .addComponent(jInput2TextField))
                                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                            .addComponent(jInput1Label)
                                            .addGap(18, 18, 18)
                                            .addComponent(jInput1TextField, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(jAddButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSubtractButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)))
                                    .addGroup(jCalculatorPanelLayout.createParallelGroup()
                                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jOutputLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(jOutputTextField, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(jMultButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                            .addGap(72, 72, 72)
                                            .addComponent(jDivButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                    .addComponent(jPowerButton, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCylinderVolumeButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSphereVolumeButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPyramidVolumeButton)))
                            .addContainerGap(343, Short.MAX_VALUE))
                );
                jCalculatorPanelLayout.setVerticalGroup(
                    jCalculatorPanelLayout.createParallelGroup()
                        .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jCalculatorPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jInput1Label)
                                .addComponent(jOutputLabel)
                                .addComponent(jInput1TextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jOutputTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(jCalculatorPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jInput2Label)
                                .addComponent(jInput2TextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(jCalculatorPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jAddButton)
                                .addComponent(jSubtractButton)
                                .addComponent(jMultButton)
                                .addComponent(jDivButton))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jCalculatorPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jPowerButton)
                                .addComponent(jCylinderVolumeButton)
                                .addComponent(jSphereVolumeButton)
                                .addComponent(jPyramidVolumeButton))
                            .addContainerGap(299, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

            //======== jClientListPanel ========
            {

                //======== scrollPane1 ========
                {

                    //---- jClientInfoList ----
                    jClientInfoList.addListSelectionListener(e -> jClientInfoListValueChanged(e));
                    scrollPane1.setViewportView(jClientInfoList);
                }

                //---- jFnameLabel3 ----
                jFnameLabel3.setText("First Name");

                //---- jSnameLabel ----
                jSnameLabel.setText("Surname");

                //---- jDOBLabel ----
                jDOBLabel.setText("DOB (dd/mm/yyyy)");

                //---- jHouseNumLabel ----
                jHouseNumLabel.setText("House Number");

                //---- jStreetLabel ----
                jStreetLabel.setText("Street");

                //---- jTownLabel ----
                jTownLabel.setText("Town");

                //---- jPostCodeLabel ----
                jPostCodeLabel.setText("Post Code");

                //---- jCountryLabel ----
                jCountryLabel.setText("Country");

                //---- jSaveButton ----
                jSaveButton.setText("Save");
                jSaveButton.addActionListener(e -> jaddClientSave(e));

                //---- jRemoveButton ----
                jRemoveButton.setText("Remove");
                jRemoveButton.addActionListener(e -> jRemoveButtonActionPressed(e));

                //---- jFindButton ----
                jFindButton.setText("Find");
                jFindButton.addActionListener(e -> jFindButtonPressed(e));

                GroupLayout jClientListPanelLayout = new GroupLayout(jClientListPanel);
                jClientListPanel.setLayout(jClientListPanelLayout);
                jClientListPanelLayout.setHorizontalGroup(
                    jClientListPanelLayout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jClientListPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(scrollPane1, GroupLayout.PREFERRED_SIZE, 461, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addGroup(jClientListPanelLayout.createParallelGroup()
                                .addComponent(jCountryLabel)
                                .addGroup(jClientListPanelLayout.createSequentialGroup()
                                    .addGroup(jClientListPanelLayout.createParallelGroup()
                                        .addComponent(jTownTextField, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTownLabel))
                                    .addGap(46, 46, 46)
                                    .addGroup(jClientListPanelLayout.createParallelGroup()
                                        .addComponent(jPostCodeLabel)
                                        .addComponent(jPostCodeTextField, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jDOBTextField, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDOBLabel)
                                .addGroup(jClientListPanelLayout.createSequentialGroup()
                                    .addGroup(jClientListPanelLayout.createParallelGroup()
                                        .addComponent(jHouseNumTextField, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jHouseNumLabel)
                                        .addComponent(jFnameTextField, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFnameLabel3, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58)
                                    .addGroup(jClientListPanelLayout.createParallelGroup()
                                        .addComponent(jSnameLabel, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSnameTextField, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jStreetLabel)
                                        .addComponent(jStreetTextField, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jClientListPanelLayout.createSequentialGroup()
                                    .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFindButton, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jCountryTextField, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                    .addGap(38, 38, 38)
                                    .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSaveButton, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(jRemoveButton, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))))
                            .addGap(14, 14, 14))
                );
                jClientListPanelLayout.setVerticalGroup(
                    jClientListPanelLayout.createParallelGroup()
                        .addGroup(jClientListPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(scrollPane1, GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addGap(81, 81, 81))
                        .addGroup(jClientListPanelLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jFnameLabel3)
                                .addComponent(jSnameLabel))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jFnameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSnameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jDOBLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDOBTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jHouseNumLabel)
                                .addComponent(jStreetLabel))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jHouseNumTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jStreetTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jTownLabel)
                                .addComponent(jPostCodeLabel))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jTownTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPostCodeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jCountryLabel)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jClientListPanelLayout.createParallelGroup()
                                .addComponent(jCountryTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSaveButton, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jClientListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRemoveButton, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                .addComponent(jFindButton, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                            .addGap(0, 62, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Client List", jClientListPanel);

            //======== jHeadOfficePanel ========
            {

                //---- jHeadOfficeButton ----
                jHeadOfficeButton.setText("Display");
                jHeadOfficeButton.addActionListener(e -> jHeadOfficeButtonActionPerformed(e));

                //---- jHeadOfficeTextArea ----
                jHeadOfficeTextArea.setColumns(20);
                jHeadOfficeTextArea.setRows(5);

                GroupLayout jHeadOfficePanelLayout = new GroupLayout(jHeadOfficePanel);
                jHeadOfficePanel.setLayout(jHeadOfficePanelLayout);
                jHeadOfficePanelLayout.setHorizontalGroup(
                    jHeadOfficePanelLayout.createParallelGroup()
                        .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                            .addGroup(jHeadOfficePanelLayout.createParallelGroup()
                                .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jHeadOfficeTextArea, GroupLayout.PREFERRED_SIZE, 341, GroupLayout.PREFERRED_SIZE))
                                .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(jHeadOfficeButton)))
                            .addContainerGap(501, Short.MAX_VALUE))
                );
                jHeadOfficePanelLayout.setVerticalGroup(
                    jHeadOfficePanelLayout.createParallelGroup()
                        .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jHeadOfficeTextArea, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jHeadOfficeButton)
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Head Office", jHeadOfficePanel);

            //======== jEditHeadOfficePanel ========
            {

                //---- JNameEditLabel ----
                JNameEditLabel.setText("Name");

                //---- jOpeningHoursEditLabel ----
                jOpeningHoursEditLabel.setText("Opening Hours");

                //---- jHouseNoEditLabel ----
                jHouseNoEditLabel.setText("House No");

                //---- jStreetEditLabel ----
                jStreetEditLabel.setText("Street");

                //---- jCityEditLabel ----
                jCityEditLabel.setText("City");

                //---- jPostcodeEditLabel ----
                jPostcodeEditLabel.setText("Postcode");

                //---- jCountryEditLabel ----
                jCountryEditLabel.setText("Country");

                //---- jStreetEditTextField ----
                jStreetEditTextField.addActionListener(e -> jStreetEditTextFieldActionPerformed(e));

                //---- jPostCodeEditTextField ----
                jPostCodeEditTextField.addActionListener(e -> jPostCodeEditTextFieldActionPerformed(e));

                //---- jButton1 ----
                jButton1.setText("Save");
                jButton1.addActionListener(e -> jButton1ActionPerformed(e));

                GroupLayout jEditHeadOfficePanelLayout = new GroupLayout(jEditHeadOfficePanel);
                jEditHeadOfficePanel.setLayout(jEditHeadOfficePanelLayout);
                jEditHeadOfficePanelLayout.setHorizontalGroup(
                    jEditHeadOfficePanelLayout.createParallelGroup()
                        .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup()
                                        .addComponent(jOpeningHoursEditLabel)
                                        .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(JNameEditLabel)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jNameEditTextField)
                                        .addComponent(jOpeningHoursEditTextField, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)
                                    .addGroup(jEditHeadOfficePanelLayout.createParallelGroup()
                                        .addComponent(jHouseNoEditLabel)
                                        .addComponent(jStreetEditLabel)
                                        .addComponent(jCityEditLabel)
                                        .addComponent(jPostcodeEditLabel)
                                        .addComponent(jCountryEditLabel)))
                                .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(10, 10, 10)))
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCountryEditTextField)
                                .addComponent(jPostCodeEditTextField)
                                .addComponent(jCityEditTextField)
                                .addComponent(jStreetEditTextField)
                                .addComponent(jHouseNoEditTextField, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(336, Short.MAX_VALUE))
                );
                jEditHeadOfficePanelLayout.setVerticalGroup(
                    jEditHeadOfficePanelLayout.createParallelGroup()
                        .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(JNameEditLabel)
                                .addComponent(jHouseNoEditLabel)
                                .addComponent(jNameEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jHouseNoEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jOpeningHoursEditLabel)
                                .addComponent(jOpeningHoursEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jStreetEditLabel)
                                .addComponent(jStreetEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jCityEditLabel)
                                .addComponent(jCityEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jPostcodeEditLabel)
                                .addComponent(jPostCodeEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jCountryEditLabel)
                                .addComponent(jCountryEditTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addComponent(jButton1)
                            .addContainerGap(200, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Edit Head Office", jEditHeadOfficePanel);

            //======== jBranchListPenel ========
            {

                //======== scrollPane2 ========
                {
                    scrollPane2.setViewportView(jBranchListTextArea);
                }

                //---- JBranchListDisplay ----
                JBranchListDisplay.setText("Display");
                JBranchListDisplay.addActionListener(e -> JBranchListDisplay(e));

                GroupLayout jBranchListPenelLayout = new GroupLayout(jBranchListPenel);
                jBranchListPenel.setLayout(jBranchListPenelLayout);
                jBranchListPenelLayout.setHorizontalGroup(
                    jBranchListPenelLayout.createParallelGroup()
                        .addGroup(jBranchListPenelLayout.createSequentialGroup()
                            .addComponent(scrollPane2, GroupLayout.PREFERRED_SIZE, 577, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 271, Short.MAX_VALUE))
                        .addGroup(jBranchListPenelLayout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(JBranchListDisplay, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(512, Short.MAX_VALUE))
                );
                jBranchListPenelLayout.setVerticalGroup(
                    jBranchListPenelLayout.createParallelGroup()
                        .addGroup(jBranchListPenelLayout.createSequentialGroup()
                            .addComponent(scrollPane2, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JBranchListDisplay, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 135, Short.MAX_VALUE))
                );
            }
            jMainTabbedPane.addTab("Branch List", jBranchListPenel);

            //======== jAddBranchPanel ========
            {

                //======== panel2 ========
                {

                    //---- jFnameLabel2 ----
                    jFnameLabel2.setText("First Name");

                    //---- jSnameLabel2 ----
                    jSnameLabel2.setText("Surname");

                    //---- jDOBLabel2 ----
                    jDOBLabel2.setText("DOB");

                    //---- jHouseNumLabel2 ----
                    jHouseNumLabel2.setText("House Number");

                    //---- jStreetLabel2 ----
                    jStreetLabel2.setText("Street");

                    //---- jTownLabel2 ----
                    jTownLabel2.setText("Town");

                    //---- jPostCodeLabel2 ----
                    jPostCodeLabel2.setText("Post Code");

                    //---- jCountryLabel2 ----
                    jCountryLabel2.setText("Country");

                    //---- label1 ----
                    label1.setText("Manager");

                    //---- jSaveBranchButton ----
                    jSaveBranchButton.setText("Save");
                    jSaveBranchButton.addActionListener(e -> jSaveBranch(e));

                    GroupLayout panel2Layout = new GroupLayout(panel2);
                    panel2.setLayout(panel2Layout);
                    panel2Layout.setHorizontalGroup(
                        panel2Layout.createParallelGroup()
                            .addGroup(panel2Layout.createParallelGroup()
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jFnameLabel2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jSnameLabel2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jFnameTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jSnameTextField2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jDOBLabel2)
                                        .addComponent(jDOBTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jHouseNumLabel2)
                                            .addGap(30, 30, 30)
                                            .addComponent(jStreetLabel2))
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jHouseNumTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jStreetTextField2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jTownLabel2)
                                            .addGap(87, 87, 87)
                                            .addComponent(jPostCodeLabel2))
                                        .addGroup(panel2Layout.createSequentialGroup()
                                            .addComponent(jTownTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jPostCodeTextField2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCountryLabel2)
                                        .addComponent(jCountryTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap(157, Short.MAX_VALUE)
                                .addGroup(panel2Layout.createParallelGroup()
                                    .addGroup(GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                        .addComponent(label1, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155))
                                    .addGroup(GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                        .addComponent(jSaveBranchButton, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                    );
                    panel2Layout.setVerticalGroup(
                        panel2Layout.createParallelGroup()
                            .addGroup(panel2Layout.createParallelGroup()
                                .addGroup(panel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jFnameLabel2)
                                        .addComponent(jSnameLabel2))
                                    .addGap(6, 6, 6)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jFnameTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSnameTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jDOBLabel2)
                                    .addGap(6, 6, 6)
                                    .addComponent(jDOBTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jHouseNumLabel2)
                                        .addComponent(jStreetLabel2))
                                    .addGap(6, 6, 6)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jHouseNumTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jStreetTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jTownLabel2)
                                        .addComponent(jPostCodeLabel2))
                                    .addGap(6, 6, 6)
                                    .addGroup(panel2Layout.createParallelGroup()
                                        .addComponent(jTownTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPostCodeTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addComponent(jCountryLabel2)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCountryTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(label1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                                .addComponent(jSaveBranchButton)
                                .addGap(36, 36, 36))
                    );
                }

                //======== panel3 ========
                {

                    //---- JNameEditLabel2 ----
                    JNameEditLabel2.setText("Name");

                    //---- jOpeningHoursEditLabel2 ----
                    jOpeningHoursEditLabel2.setText("Opening Hours");

                    //---- jHouseNoEditLabel2 ----
                    jHouseNoEditLabel2.setText("House No");

                    //---- jStreetEditLabel2 ----
                    jStreetEditLabel2.setText("Street");

                    //---- jCityEditLabel2 ----
                    jCityEditLabel2.setText("City");

                    //---- jPostcodeEditLabel2 ----
                    jPostcodeEditLabel2.setText("Postcode");

                    //---- jCountryEditLabel2 ----
                    jCountryEditLabel2.setText("Country");

                    //---- jStreetEditTextField2 ----
                    jStreetEditTextField2.addActionListener(e -> jStreetEditTextFieldActionPerformed(e));

                    //---- jPostCodeEditTextField2 ----
                    jPostCodeEditTextField2.addActionListener(e -> jPostCodeEditTextFieldActionPerformed(e));

                    //---- label2 ----
                    label2.setText("Branch");

                    GroupLayout panel3Layout = new GroupLayout(panel3);
                    panel3.setLayout(panel3Layout);
                    panel3Layout.setHorizontalGroup(
                        panel3Layout.createParallelGroup()
                            .addGroup(panel3Layout.createParallelGroup()
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addGap(1217, 1217, Short.MAX_VALUE)
                                    .addComponent(jStreetEditLabel2)
                                    .addGap(24, 24, 24)
                                    .addComponent(jStreetEditTextField2, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup()
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(panel3Layout.createParallelGroup()
                                            .addComponent(JNameEditLabel2)
                                            .addComponent(jNameEditTextField2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOpeningHoursEditLabel2)
                                            .addComponent(jOpeningHoursEditTextField2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66)
                                        .addGroup(panel3Layout.createParallelGroup()
                                            .addComponent(jCountryEditTextField2, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCountryEditLabel2)
                                            .addComponent(jPostcodeEditLabel2)
                                            .addComponent(jCityEditLabel2)
                                            .addComponent(jHouseNoEditTextField2, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jHouseNoEditLabel2)
                                            .addComponent(jCityEditTextField2, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPostCodeEditTextField2, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(label2)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    panel3Layout.setVerticalGroup(
                        panel3Layout.createParallelGroup()
                            .addGroup(panel3Layout.createParallelGroup()
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addGap(0, 231, Short.MAX_VALUE)
                                    .addGroup(panel3Layout.createParallelGroup()
                                        .addComponent(jStreetEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel3Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jStreetEditLabel2)))
                                    .addGap(0, 245, Short.MAX_VALUE)))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(label2)
                                .addGap(18, 18, 18)
                                .addGroup(panel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(JNameEditLabel2)
                                    .addComponent(jHouseNoEditLabel2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jNameEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHouseNoEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jOpeningHoursEditLabel2)
                                    .addComponent(jCityEditLabel2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel3Layout.createParallelGroup()
                                    .addComponent(jOpeningHoursEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCityEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPostcodeEditLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPostCodeEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCountryEditLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCountryEditTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(180, Short.MAX_VALUE))
                    );
                }

                GroupLayout jAddBranchPanelLayout = new GroupLayout(jAddBranchPanel);
                jAddBranchPanel.setLayout(jAddBranchPanelLayout);
                jAddBranchPanelLayout.setHorizontalGroup(
                    jAddBranchPanelLayout.createParallelGroup()
                        .addGroup(jAddBranchPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panel3, GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                );
                jAddBranchPanelLayout.setVerticalGroup(
                    jAddBranchPanelLayout.createParallelGroup()
                        .addGroup(jAddBranchPanelLayout.createSequentialGroup()
                            .addComponent(panel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addComponent(panel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
            }
            jMainTabbedPane.addTab("Add Branch", jAddBranchPanel);
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jMainTabbedPane, GroupLayout.PREFERRED_SIZE, 848, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jMainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jMainTabbedPane, GroupLayout.PREFERRED_SIZE, 512, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jMainPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        
        
        if (theUser.isUser(jNameTextField.getText(), jPasswordTextField.getText())){


            jMainTabbedPane.addTab("Calculator", jTabInMemory[0]);
            jMainTabbedPane.addTab("HeadOffice", jTabInMemory[2]);

            switch(theUser.getRole()){
                case("Bank Manager") -> {
                    jMainTabbedPane.addTab("Client List", jTabInMemory[1]);
                    jMainTabbedPane.addTab("Edit Head Office", jTabInMemory[3]);
                    jMainTabbedPane.addTab("Client List", jTabInMemory[4]);
                    jMainTabbedPane.addTab("Add Branch", jTabInMemory[5]);
                }
                case("Bank Employee"),("Bank Advisor"),("Bank Admin"),("Bank Customer") -> {
                    //jMainTabbedPane.addTab("Calculator", jTabInMemory[0]);
                    //jMainTabbedPane.addTab("HeadOffice", jTabInMemory[2]);
                }
                default -> {
                }
            }
            
            jStatusMessageLabel.setText(jNameTextField.getText() + " is logged in...");


            jMainTabbedPane.setSelectedIndex(1);
        } else {
            jStatusMessageLabel.setText("Cannot Login, please check Name and Password.");
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jInput1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInput1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInput1TextFieldActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 + input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jOutputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOutputTextFieldActionPerformed

    private void jSubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubtractButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 - input2;
        
        String result = String.format("%.5f",output);
        
        jOutputTextField.setText(result);
    }//GEN-LAST:event_jSubtractButtonActionPerformed

    private void jMultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 * input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jMultButtonActionPerformed
    private double power(double base, int exponent) {
        
        double power = 1;
        
        for (int i = 1; i <= exponent; i++) {
            power = power * base;
        }
        
        return power;
    }
    
    private void jDivButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        if (input2==0) {
            jOutputTextField.setText("Cannot Divide By 0.");
        } else {
            double output = input1 / input2;
        
            jOutputTextField.setText(String.valueOf(output));
        } 
    }//GEN-LAST:event_jDivButtonActionPerformed

    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        
        try{
            int input2 = Integer.parseInt(jInput2TextField.getText());
            
            double output = power(input1, input2);
        
            jOutputTextField.setText(String.valueOf(output));
            
        }catch (NumberFormatException ex) {
            jOutputTextField.setText("Cannot use decimal as power");
        }
        
        
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jCylinderVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double pi = 3.141592653589793238;
        
        double output = pi * input2 * power(input1 , 2);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jCylinderVolumeButtonActionPerformed

    private void jSphereVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSphereVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        
        double pi = 3.141592653589793238;
        
        double output = pi * (4/3) * power(input1 , 3);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jSphereVolumeButtonActionPerformed

    private void jPyramidVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPyramidVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = ((double) 1 /3) * input2 * power(input1 , 2);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jPyramidVolumeButtonActionPerformed

    private void jHeadOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeadOfficeButtonActionPerformed
        // TODO add your handling code here:
        theHeadOfficeBranch.Display(jHeadOfficeTextArea);
    }//GEN-LAST:event_jHeadOfficeButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // TODO add your handling code here:
        if (theUser.isRegistered(jNameTextField.getText(), jPasswordTextField.getText(), "")){
            jStatusMessageLabel.setText("The " + jNameTextField.getText() + " is registered... Please Log In Now.");
        } else {
            jStatusMessageLabel.setText("Cannot register the user");
        }
        
      
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jStreetEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStreetEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStreetEditTextFieldActionPerformed

    private void jPostCodeEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPostCodeEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPostCodeEditTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        theHeadOfficeBranch.Edit(jOpeningHoursEditTextField.getText(),"");
        theHeadOfficeBranch.addressEdit(jNameEditTextField.getText(), "", Integer.valueOf(jHouseNoEditTextField.getText()), jStreetEditTextField.getText(), "", jPostCodeEditTextField.getText(), jCityEditTextField.getText(), jCountryEditTextField.getText());
        theHeadOfficeBranch.SaveToFile("Branches/HeadOfficeBranch.txt");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonActionPerformed
        // TODO add your handling code here:
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.setSelectedIndex(0);
        
        theUser.resetRole();
        
        jStatusMessageLabel.setText("Logged Out.");
    }//GEN-LAST:event_jLogOutButtonActionPerformed


    private void jaddClientSave(ActionEvent e) {
        // TODO add your code here
        Person newClient = fieldsToPerson();

        newClient.createCurrent(theHeadOfficeBranch.getSortCode(), "Head Office", 1.2);
        newClient.createISA(theHeadOfficeBranch.getSortCode(), "Head Office", 1.2);
        newClient.createSavings(theHeadOfficeBranch.getSortCode(), "Head Office", 1.2, 1.1);
        
        BankClients.addClient(newClient);


        // Save to file
        BankClients.SaveToFile("Accounts/BankClients.txt");
    }

    private void jRemoveButtonActionPressed(ActionEvent e) {
        Person removedPerson = new Person();

        removedPerson.setFirstName(jFnameTextField.getText());
        removedPerson.setSurname(jSnameTextField.getText());
        removedPerson.setDOB(jDOBTextField.getText());

        BankClients.removeClient(BankClients.find(removedPerson));

        BankClients.SaveToFile("Accounts/BankClients.txt");
    }

    private void JBranchListDisplay(ActionEvent e) {
        // TODO add your code here
        BankBranches.Display(jBranchListTextArea);
    }

    private void jSaveBranch(ActionEvent e) {
        // TODO add your code here
        Person branchManager = new Person();
        Branch newBranch = new Branch();

        LocalDate date = LocalDate.now();

        branchManager.Edit(jFnameTextField2.getText(), jSnameTextField2.getText(), jDOBTextField2.getText(), date.format(DateTimeFormatter.ofPattern("d/MM/uuuu")));

        branchManager.editAddress("", Integer.valueOf(jHouseNumTextField2.getText()), jStreetTextField2.getText(), "", jPostCodeTextField2.getText(), jTownTextField2.getText(), jCountryTextField2.getText());
        
        newBranch.assignManager(branchManager);

        newBranch.Edit(jOpeningHoursEditTextField2.getText(),"00-00-00");
        newBranch.addressEdit(jNameEditTextField2.getText(), "", Integer.valueOf(jHouseNoEditTextField2.getText()), jStreetEditTextField2.getText(), "", jPostCodeEditTextField2.getText(), jCityEditTextField2.getText(), jCountryEditTextField2.getText());

        BankBranches.addBranch(newBranch);

        BankBranches.SaveToFile();
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
        
     
    }

    
    private Branch theHeadOfficeBranch;
    private Person theManagerPerson;
    private IAddress theHeadOfficeAddress;
    private java.awt.Component[] jTabInMemory;
    private User theUser;

    private CustomerList BankClients;
    
    private BranchList BankBranches;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Ethan Deeley (2282321)
    private JMenuBar jMenuBarMain;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JPanel jMainPanel;
    private JPanel jStatusPanel;
    private JLabel jStatusMessageLabel;
    private JLabel jStatusAnimationLabel;
    private JProgressBar jProgressCompletionBar;
    private JTabbedPane jMainTabbedPane;
    private JPanel jLoginPanel;
    private JLabel jNameLabel;
    private JTextField jNameTextField;
    private JButton jLoginButton;
    private JLabel jPasswordLabel;
    private JPasswordField jPasswordTextField;
    private JButton jRegisterButton;
    private JButton jLogOutButton;
    private JPanel jCalculatorPanel;
    private JLabel jInput1Label;
    private JLabel jInput2Label;
    private JLabel jOutputLabel;
    private JTextField jInput1TextField;
    private JTextField jInput2TextField;
    private JTextField jOutputTextField;
    private JButton jAddButton;
    private JButton jSubtractButton;
    private JButton jMultButton;
    private JButton jDivButton;
    private JButton jPowerButton;
    private JButton jCylinderVolumeButton;
    private JButton jSphereVolumeButton;
    private JButton jPyramidVolumeButton;
    private JPanel jClientListPanel;
    private JScrollPane scrollPane1;
    private JList jClientInfoList;
    private JLabel jFnameLabel3;
    private JLabel jSnameLabel;
    private JTextField jFnameTextField;
    private JTextField jSnameTextField;
    private JLabel jDOBLabel;
    private JTextField jDOBTextField;
    private JLabel jHouseNumLabel;
    private JTextField jHouseNumTextField;
    private JLabel jStreetLabel;
    private JTextField jStreetTextField;
    private JLabel jTownLabel;
    private JLabel jPostCodeLabel;
    private JTextField jTownTextField;
    private JTextField jPostCodeTextField;
    private JLabel jCountryLabel;
    private JTextField jCountryTextField;
    private JButton jSaveButton;
    private JButton jRemoveButton;
    private JButton jFindButton;
    private JPanel jHeadOfficePanel;
    private JButton jHeadOfficeButton;
    private JTextArea jHeadOfficeTextArea;
    private JPanel jEditHeadOfficePanel;
    private JLabel JNameEditLabel;
    private JTextField jNameEditTextField;
    private JLabel jOpeningHoursEditLabel;
    private JTextField jOpeningHoursEditTextField;
    private JLabel jHouseNoEditLabel;
    private JLabel jStreetEditLabel;
    private JLabel jCityEditLabel;
    private JLabel jPostcodeEditLabel;
    private JLabel jCountryEditLabel;
    private JTextField jHouseNoEditTextField;
    private JTextField jStreetEditTextField;
    private JTextField jCityEditTextField;
    private JTextField jPostCodeEditTextField;
    private JTextField jCountryEditTextField;
    private JButton jButton1;
    private JPanel jBranchListPenel;
    private JScrollPane scrollPane2;
    private JTextArea jBranchListTextArea;
    private JButton JBranchListDisplay;
    private JPanel jAddBranchPanel;
    private JPanel panel2;
    private JLabel jFnameLabel2;
    private JLabel jSnameLabel2;
    private JTextField jFnameTextField2;
    private JTextField jSnameTextField2;
    private JLabel jDOBLabel2;
    private JTextField jDOBTextField2;
    private JLabel jHouseNumLabel2;
    private JTextField jHouseNumTextField2;
    private JLabel jStreetLabel2;
    private JTextField jStreetTextField2;
    private JLabel jTownLabel2;
    private JLabel jPostCodeLabel2;
    private JTextField jTownTextField2;
    private JTextField jPostCodeTextField2;
    private JLabel jCountryLabel2;
    private JTextField jCountryTextField2;
    private JLabel label1;
    private JButton jSaveBranchButton;
    private JPanel panel3;
    private JLabel JNameEditLabel2;
    private JTextField jNameEditTextField2;
    private JLabel jOpeningHoursEditLabel2;
    private JTextField jOpeningHoursEditTextField2;
    private JLabel jHouseNoEditLabel2;
    private JLabel jStreetEditLabel2;
    private JLabel jCityEditLabel2;
    private JLabel jPostcodeEditLabel2;
    private JLabel jCountryEditLabel2;
    private JTextField jHouseNoEditTextField2;
    private JTextField jStreetEditTextField2;
    private JTextField jCityEditTextField2;
    private JTextField jPostCodeEditTextField2;
    private JTextField jCountryEditTextField2;
    private JLabel label2;
    // End of variables declaration//GEN-END:variables
}
