/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myfirstapplication;

/**
 *
 * @author ethan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        theHeadOfficeBranch = new Branch();
        
        theUser = new User();
        
        // Tab Code
        jTabInMemory = new java.awt.Component[3];
        
        for(int i = 0; i < (jMainTabbedPane.getTabCount() + 1); i++){
            jTabInMemory[i] = (jMainTabbedPane.getComponentAt(1));
            jMainTabbedPane.remove(1);
        }
        
        jMainTabbedPane.setSelectedIndex(0);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jStatusPanel = new javax.swing.JPanel();
        jStatusMessageLabel = new javax.swing.JLabel();
        jStatusAnimationLabel = new javax.swing.JLabel();
        jProgressCompletionBar = new javax.swing.JProgressBar();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLoginButton = new javax.swing.JButton();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JTextField();
        jRegisterButton = new javax.swing.JButton();
        jLogOutButton = new javax.swing.JButton();
        jCalculatorPanel = new javax.swing.JPanel();
        jInput1Label = new javax.swing.JLabel();
        jInput2Label = new javax.swing.JLabel();
        jOutputLabel = new javax.swing.JLabel();
        jInput1TextField = new javax.swing.JTextField();
        jInput2TextField = new javax.swing.JTextField();
        jOutputTextField = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jSubtractButton = new javax.swing.JButton();
        jMultButton = new javax.swing.JButton();
        jDivButton = new javax.swing.JButton();
        jPowerButton = new javax.swing.JButton();
        jCylinderVolumeButton = new javax.swing.JButton();
        jSphereVolumeButton = new javax.swing.JButton();
        jPyramidVolumeButton = new javax.swing.JButton();
        jHeadOfficePanel = new javax.swing.JPanel();
        jHeadOfficeButton = new javax.swing.JButton();
        jHeadOfficeTextArea = new javax.swing.JTextArea();
        jEditHeadOfficePanel = new javax.swing.JPanel();
        JNameEditLabel = new javax.swing.JLabel();
        jNameEditTextField = new javax.swing.JTextField();
        jOpeningHoursEditLabel = new javax.swing.JLabel();
        jOpeningHoursEditTextField = new javax.swing.JTextField();
        jHouseNoEditLabel = new javax.swing.JLabel();
        jStreetEditLabel = new javax.swing.JLabel();
        jCityEditLabel = new javax.swing.JLabel();
        jPostcodeEditLabel = new javax.swing.JLabel();
        jCountryEditLabel = new javax.swing.JLabel();
        jHouseNoEditTextField = new javax.swing.JTextField();
        jStreetEditTextField = new javax.swing.JTextField();
        jCityEditTextField = new javax.swing.JTextField();
        jPostCodeEditTextField = new javax.swing.JTextField();
        jCountryEditTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(74, 74, 72));

        jStatusPanel.setBackground(new java.awt.Color(74, 74, 72));
        jStatusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jStatusPanel.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N

        jStatusMessageLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jStatusMessageLabel.setText("My First Application is running.");

        jStatusAnimationLabel.setText("jLabel2");

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStatusMessageLabel)
                    .addComponent(jStatusAnimationLabel)
                    .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 174, Short.MAX_VALUE))
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addComponent(jStatusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatusAnimationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 246, Short.MAX_VALUE))
        );

        jNameLabel.setText("Name:");
        jNameLabel.setToolTipText("");

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jPasswordLabel.setText("Password:");

        jRegisterButton.setText("Register");
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        jLogOutButton.setText("Log Out");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNameLabel)
                .addGap(264, 264, 264))
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jPasswordLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRegisterButton))
                            .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 213, Short.MAX_VALUE))
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLogOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addComponent(jNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton)
                    .addComponent(jRegisterButton))
                .addGap(18, 18, 18)
                .addComponent(jLogOutButton)
                .addGap(0, 301, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jInput1Label.setText("Input 1");

        jInput2Label.setText("Input 2");

        jOutputLabel.setText("Output");

        jInput1TextField.setText("0.0");
        jInput1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInput1TextFieldActionPerformed(evt);
            }
        });

        jInput2TextField.setText("0.0");

        jOutputTextField.setText("0.0");
        jOutputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutputTextFieldActionPerformed(evt);
            }
        });

        jAddButton.setText("+");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jSubtractButton.setText("-");
        jSubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubtractButtonActionPerformed(evt);
            }
        });

        jMultButton.setText("*");
        jMultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultButtonActionPerformed(evt);
            }
        });

        jDivButton.setText("/");
        jDivButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivButtonActionPerformed(evt);
            }
        });

        jPowerButton.setText("X^y");
        jPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerButtonActionPerformed(evt);
            }
        });

        jCylinderVolumeButton.setText("Cylinder Vol");
        jCylinderVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCylinderVolumeButtonActionPerformed(evt);
            }
        });

        jSphereVolumeButton.setText("Sphere Vol");
        jSphereVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSphereVolumeButtonActionPerformed(evt);
            }
        });

        jPyramidVolumeButton.setText("Pyramid Vol");
        jPyramidVolumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPyramidVolumeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jInput2Label)
                                .addGap(18, 18, 18)
                                .addComponent(jInput2TextField))
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jInput1Label)
                                .addGap(18, 18, 18)
                                .addComponent(jInput1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSubtractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jOutputLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jMultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jDivButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addComponent(jPowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCylinderVolumeButton)
                        .addGap(18, 18, 18)
                        .addComponent(jSphereVolumeButton)
                        .addGap(18, 18, 18)
                        .addComponent(jPyramidVolumeButton)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInput1Label)
                    .addComponent(jOutputLabel)
                    .addComponent(jInput1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInput2Label)
                    .addComponent(jInput2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jSubtractButton)
                    .addComponent(jMultButton)
                    .addComponent(jDivButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPowerButton)
                    .addComponent(jCylinderVolumeButton)
                    .addComponent(jSphereVolumeButton)
                    .addComponent(jPyramidVolumeButton))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Calculator", jCalculatorPanel);

        jHeadOfficeButton.setText("Display");
        jHeadOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeadOfficeButtonActionPerformed(evt);
            }
        });

        jHeadOfficeTextArea.setColumns(20);
        jHeadOfficeTextArea.setRows(5);

        javax.swing.GroupLayout jHeadOfficePanelLayout = new javax.swing.GroupLayout(jHeadOfficePanel);
        jHeadOfficePanel.setLayout(jHeadOfficePanelLayout);
        jHeadOfficePanelLayout.setHorizontalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addGroup(jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jHeadOfficeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jHeadOfficeButton)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jHeadOfficePanelLayout.setVerticalGroup(
            jHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadOfficePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHeadOfficeTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHeadOfficeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("HeadOffice", jHeadOfficePanel);

        JNameEditLabel.setText("Name");

        jOpeningHoursEditLabel.setText("Opening Hours");

        jHouseNoEditLabel.setText("House No");

        jStreetEditLabel.setText("Street");

        jCityEditLabel.setText("City");

        jPostcodeEditLabel.setText("Postcode");

        jCountryEditLabel.setText("Country");

        jStreetEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStreetEditTextFieldActionPerformed(evt);
            }
        });

        jPostCodeEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPostCodeEditTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEditHeadOfficePanelLayout = new javax.swing.GroupLayout(jEditHeadOfficePanel);
        jEditHeadOfficePanel.setLayout(jEditHeadOfficePanelLayout);
        jEditHeadOfficePanelLayout.setHorizontalGroup(
            jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                        .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jOpeningHoursEditLabel))
                            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(JNameEditLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNameEditTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jOpeningHoursEditTextField))
                        .addGap(35, 35, 35)
                        .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHouseNoEditLabel)
                            .addComponent(jStreetEditLabel)
                            .addComponent(jCityEditLabel)
                            .addComponent(jPostcodeEditLabel)
                            .addComponent(jCountryEditLabel)))
                    .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)))
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCountryEditTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jPostCodeEditTextField)
                    .addComponent(jCityEditTextField)
                    .addComponent(jStreetEditTextField)
                    .addComponent(jHouseNoEditTextField))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jEditHeadOfficePanelLayout.setVerticalGroup(
            jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditHeadOfficePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNameEditLabel)
                    .addComponent(jHouseNoEditLabel)
                    .addComponent(jNameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHouseNoEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOpeningHoursEditLabel)
                    .addComponent(jOpeningHoursEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStreetEditLabel)
                    .addComponent(jStreetEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCityEditLabel)
                    .addComponent(jCityEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPostcodeEditLabel)
                    .addComponent(jPostCodeEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditHeadOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCountryEditLabel)
                    .addComponent(jCountryEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Edit Head Office", jEditHeadOfficePanel);

        jMenuBarMain.setBackground(new java.awt.Color(74, 74, 72));
        jMenuBarMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 74, 72)));
        jMenuBarMain.setForeground(new java.awt.Color(86, 98, 70));

        jMenu1.setBackground(new java.awt.Color(0, 0, 65));
        jMenu1.setText("File");
        jMenuBarMain.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBarMain.add(jMenu2);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMainTabbedPane.getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        
        
        if (theUser.isUser(jNameTextField.getText(), jPasswordTextField.getText())){
            
            switch(theUser.getRole()){
                case("Bank Manager") -> {
                    jMainTabbedPane.addTab("Calculator", jTabInMemory[0]);
                    jMainTabbedPane.addTab("HeadOffice", jTabInMemory[1]);
                    jMainTabbedPane.addTab("EditHeadOffice", jTabInMemory[2]);
                }
                case("Bank Employee"),("Bank Advisor"),("Bank Admin"),("Bank Customer") -> {
                    jMainTabbedPane.addTab("Calculator", jTabInMemory[0]);
                    jMainTabbedPane.addTab("HeadOffice", jTabInMemory[1]);
                }
                default -> {
                }
            }
            
            jStatusMessageLabel.setText(jNameTextField.getText() + " is logged in...");
        
            jMainTabbedPane.addTab("Calculator", jTabInMemory[0]);
            jMainTabbedPane.addTab("HeadOffice", jTabInMemory[1]);

            jMainTabbedPane.setSelectedIndex(1);
        } else {
            jStatusMessageLabel.setText("Cannot Login, please check Name and Password.");
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jInput1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInput1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInput1TextFieldActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 + input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jOutputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOutputTextFieldActionPerformed

    private void jSubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubtractButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 - input2;
        
        String result = String.format("%.5f",output);
        
        jOutputTextField.setText(result);
    }//GEN-LAST:event_jSubtractButtonActionPerformed

    private void jMultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = input1 * input2;
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jMultButtonActionPerformed
    private double power(double base, int exponent) {
        
        double power = 1;
        
        for (int i = 1; i <= exponent; i++) {
            power = power * base;
        }
        
        return power;
    }
    
    private void jDivButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        if (input2==0) {
            jOutputTextField.setText("Cannot Divide By 0.");
        } else {
            double output = input1 / input2;
        
            jOutputTextField.setText(String.valueOf(output));
        } 
    }//GEN-LAST:event_jDivButtonActionPerformed

    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        
        try{
            int input2 = Integer.parseInt(jInput2TextField.getText());
            
            double output = power(input1, input2);
        
            jOutputTextField.setText(String.valueOf(output));
            
        }catch (NumberFormatException ex) {
            jOutputTextField.setText("Cannot use decimal as power");
        }
        
        
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jCylinderVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCylinderVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double pi = 3.141592653589793238;
        
        double output = pi * input2 * power(input1 , 2);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jCylinderVolumeButtonActionPerformed

    private void jSphereVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSphereVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        
        double pi = 3.141592653589793238;
        
        double output = pi * (4/3) * power(input1 , 3);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jSphereVolumeButtonActionPerformed

    private void jPyramidVolumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPyramidVolumeButtonActionPerformed
        // TODO add your handling code here:
        double input1 = Double.parseDouble(jInput1TextField.getText());
        double input2 = Double.parseDouble(jInput2TextField.getText());
        
        double output = (1/3) * input2 * power(input1 , 2);
        
        jOutputTextField.setText(String.valueOf(output));
    }//GEN-LAST:event_jPyramidVolumeButtonActionPerformed

    private void jHeadOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeadOfficeButtonActionPerformed
        // TODO add your handling code here:
        theHeadOfficeBranch.Display(jHeadOfficeTextArea);
    }//GEN-LAST:event_jHeadOfficeButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // TODO add your handling code here:
        if (theUser.isRegistered(jNameTextField.getText(), jPasswordTextField.getText(), "")){
            jStatusMessageLabel.setText("The " + jNameTextField.getText() + " is registered... Please Log In Now.");
        } else {
            jStatusMessageLabel.setText("Cannot register the user");
        }
        
      
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jStreetEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStreetEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStreetEditTextFieldActionPerformed

    private void jPostCodeEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPostCodeEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPostCodeEditTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        theHeadOfficeBranch.Edit(jOpeningHoursEditTextField.getText(),"");
        theHeadOfficeBranch.addressEdit(jNameEditTextField.getText(), "", Integer.valueOf(jHouseNoEditTextField.getText()), jStreetEditTextField.getText(), "", jPostCodeEditTextField.getText(), jCityEditTextField.getText(), jCountryEditTextField.getText());
        theHeadOfficeBranch.SaveToFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonActionPerformed
        // TODO add your handling code here:
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.setSelectedIndex(0);
        
        theUser.resetRole();
        
        jStatusMessageLabel.setText("Logged Out.");
    }//GEN-LAST:event_jLogOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
        
     
    }

    
    private Branch theHeadOfficeBranch;
    private Person theManagerPerson;
    private IAddress theHeadOfficeAddress;
    private java.awt.Component[] jTabInMemory;
    private User theUser;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JNameEditLabel;
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JLabel jCityEditLabel;
    private javax.swing.JTextField jCityEditTextField;
    private javax.swing.JLabel jCountryEditLabel;
    private javax.swing.JTextField jCountryEditTextField;
    private javax.swing.JButton jCylinderVolumeButton;
    private javax.swing.JButton jDivButton;
    private javax.swing.JPanel jEditHeadOfficePanel;
    private javax.swing.JButton jHeadOfficeButton;
    private javax.swing.JPanel jHeadOfficePanel;
    private javax.swing.JTextArea jHeadOfficeTextArea;
    private javax.swing.JLabel jHouseNoEditLabel;
    private javax.swing.JTextField jHouseNoEditTextField;
    private javax.swing.JLabel jInput1Label;
    private javax.swing.JTextField jInput1TextField;
    private javax.swing.JLabel jInput2Label;
    private javax.swing.JTextField jInput2TextField;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JButton jMultButton;
    private javax.swing.JTextField jNameEditTextField;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JLabel jOpeningHoursEditLabel;
    private javax.swing.JTextField jOpeningHoursEditTextField;
    private javax.swing.JLabel jOutputLabel;
    private javax.swing.JTextField jOutputTextField;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JTextField jPostCodeEditTextField;
    private javax.swing.JLabel jPostcodeEditLabel;
    private javax.swing.JButton jPowerButton;
    private javax.swing.JProgressBar jProgressCompletionBar;
    private javax.swing.JButton jPyramidVolumeButton;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jSphereVolumeButton;
    private javax.swing.JLabel jStatusAnimationLabel;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JLabel jStreetEditLabel;
    private javax.swing.JTextField jStreetEditTextField;
    private javax.swing.JButton jSubtractButton;
    // End of variables declaration//GEN-END:variables
}
